api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "offers-function"

uid = "fb77a262-6af0-7f3b-1b65-ec2149eb864f05873439"

type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
