# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

#client_id = "11fa42f73653933ca47a9ea1e7b1e2a7"
client_id = "d6dcd2395602529382d5737d99e71030"
name = "Quantity & Breaks Discount"
application_url = "https://shopapp.cardiacambulance.com/app"
embedded = true
handle = "quantity-breaks-discount-app-1"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_script_tags,read_script_tags,write_discounts,read_discounts,write_price_rules,write_cart_transforms"

[auth]
redirect_urls = ["https://emporium.cardiacambulance.com/api/callback"]

[pos]
embedded = true
